### ISSUE TITLE
Consider using webix.min.js and webix.js?

### ISSUE THREAD

**Issue by dandv** [webix-hub/webix#155]
Right now Webix [ships](https://github.com/webix-hub/tracker/tree/master/codebase) webix.js for the minified version and webix_debug.js for the non-minified one.

The convention I've seen in the JS OSS ecosystem favors `.min.js` for minified files, and just `.js` for the debug version: [jquery](https://github.com/jquery/jquery/blob/master/Gruntfile.js#L23), [Kendo UI](https://github.com/telerik/kendo-ui-core/blob/master/Gruntfile.js#L189), [d3](https://github.com/mbostock/d3/blob/master/d3.min.js), [moment](https://github.com/moment/moment/tree/develop/min) etc.

**Comment by Zwillinge** [comment]
Implemented in Webix 6.0
