### ISSUE TITLE
Texts from webix.confirm buttons are hardcoded

### ISSUE THREAD

**Issue by mbombonato** [webix-hub/webix#315]
The button texts from alert and confirmation windows should be included on the locale packages. Doing that we can avoid repeating the button configs all the time.

`if (ok || config.ok)
    inner += button(config.ok || "OK", true,"confirm");
if (cancel || config.cancel)
    inner += button(config.cancel || "Cancel", false);`

**Comment by Zwillinge** [comment]
The default texts for modal boxes have been added to locales in Webix 5.4: https://snippet.webix.com/evs3gilu
