### ISSUE TITLE
Dynamic Loading in lists doesn't work on Android devices

### ISSUE THREAD

**Issue by JendrikD** [webix-hub/webix#316]
Snippet showing the problem: https://snippet.webix.com/yb928n7a
Tested on Galaxy S5. Doesn't work with Chromes Developer Tools on Windows either while emulating touch-devices.

**Comment by Zwillinge** [comment]
Fixed in Webix 6.1: https://docs.webix.com/desktop__whats_new_6_1.html#fixes
