### ISSUE TITLE
onBeforeAjax ignores url changes

### ISSUE THREAD

**Issue by zevenbergm** [webix-hub/webix#326]
I want to use the onBeforeAjax event to add a root to the URL; however the url variable is passed by value and not by reference. All the changes on the url will be ignored. Is it possible to convert the url to an object since these are always passed by reference. 

Looking forward to your response.

**Comment by Zwillinge** [comment]
Could you please clarify your use case? Maybe Webix [server proxies](https://docs.webix.com/desktop__server_proxy.html) would be a better solution for you.

In the mean time, the `onBeforeAjax` event allows you modify url parameters dynamically.
