### ISSUE TITLE
Replace attrib "$more"

### ISSUE THREAD

**Issue by dmitriym09** [webix-hub/webix#328]
Please replace attrib "$more" to "more" or something like that. I build the bundle with webpack/PostCSS and get an exception SyntaxError in postcss-loader:  ''Could not resolve the variable "$more" within...".
Thx!

**Comment by Zwillinge** [comment]
Fixed in 6.3.6: https://docs.webix.com/desktop__whats_new_6_3_x.html#version636

**Comment by dmitriym09** [comment]
Thanks very much!
