### ISSUE TITLE
Problem with application url when using FileManager

### ISSUE THREAD

**Issue by jakodev** [webix-hub/webix#333]
Hi, I'm using webix (v6.4) in a .Net MVC Environment and I've an issue with my **application url** and the component **FileManger**. 

Before loading the component the url of my page is (for instance): **http://my.applicationurl.com/xyz/controller/detail/123456456**

When the component is fully loaded the application url of my page change as this:
**http://my.applicationurl.com/xyz/#!/folder_root_id**

Why I'm loosing the **controller/action** part of the url?

Obviously I cannot deal with this kind of url for many reason, first of all the user cannot simply press F5 to reload the page because the source url has been turned to nothing.

Thanks in advance,
J.

**Comment by HelgaListopad** [comment]
Hi @jakodev 

By default, the navigation in the File Manager operates with `window.history` and changes the URL via `window.location.hash`.
So far this feature can be disabled with the [corresponding property](https://docs.webix.com/api__ui.filemanager_disabledhistory_config.html) (Back/Forward buttons will work as usual). 
In Webix 7.0 release, the default behaviour will be changed and the URL/window history won't be affected. 

The major changes in API for the 7.0 release are described in the [following article](https://blog.webix.com/farewell-to-the-old-year-farewell-to-the-old-code-looking-forward-to-7-0/).

**Comment by jakodev** [comment]
Thank you very much Helga! I was going crazy about this situation.

kind regards,
J.
