### ISSUE TITLE
Checkbox/label alignment is wrong only on GPL css

### ISSUE THREAD

**Issue by mbombonato** [webix-hub/webix#335]
Use this snippet and change from GPL to Pro to see the difference. The issue still exists on 7.1.
https://snippet.webix.com/yvayom9h

**Comment by HelgaListopad** [comment]
Hi @mbombonato 

Thank you for reporting the issue (relevant for Compact/Flat skins)!
As a temporary solution, please change the label positioning with the following CSS:
```
  .webix_el_checkbox .webix_label_right {
  	float:left;
  }
```
https://snippet.webix.com/pvhirvfa

**Comment by lVeliarl** [comment]
Hey @mbombonato,

We've updated our GPL package to version 7.1.4 and the related issue has been fixed, as can be seen from this example - https://snippet.webix.com/cazvftlb.

**Comment by mbombonato** [comment]
Thanks!
