### ISSUE TITLE
How get parameters for selected columns in a list

### ISSUE THREAD

**Issue by hjx777** [webix-hub/webix#346]
Hello, I'm trying to use "list" and "datatable", I need to click on an item in the list, get the number of rows of the row being clicked as a parameter, and then make an ajax request and get the data, which it will display in the datatable. May I ask how to get the number of rows in the row clicked in the list?

PS: The data sent to the list has no id value

```
var listShotSignal = {
		rows:[
                    {view:"list",
                    id:"listshotsignal",
                    select:true,
                    css:"second_text",
                    template:"#idx_signame#",
                    click:() => {
                        this.$$("metadatatable1").clearAll();
                        console.log($$("metadatatable1").getParam())
//ajax request,it needs parameters for selected columns
                        // this.getMetaData(***)
                    }
                },
                    buttons,
				]
        }
```

**Comment by mkozhukh** [comment]
Even if you have not provided IDs, they will be assigned automatically
So you can use getIndexById method

```js
click:(id) => {
    const ind = $$("listshotsignal").getIndexById(id);
```

https://docs.webix.com/api__link__ui.list_getindexbyid.html

**Comment by hjx777** [comment]
> Even if you have not provided IDs, they will be assigned automatically So you can use getIndexById method
> 
> ```js
> click:(id) => {
>     const ind = $$("listshotsignal").getIndexById(id);
> ```
> 
> https://docs.webix.com/api__link__ui.list_getindexbyid.html



> Even if you have not provided IDs, they will be assigned automatically So you can use getIndexById method
> 
> ```js
> click:(id) => {
>     const ind = $$("listshotsignal").getIndexById(id);
> ```
> 
> https://docs.webix.com/api__link__ui.list_getindexbyid.html

Thank you very much！I get it！
